# This file contains the configuration for this project.
# When you update `info` or `fileAssociations`, run `wails3 task common:update:build-assets` to update the assets.
# Note that this will overwrite any changes you have made to the assets.
version: '3'

info:
  companyName: "TOY-KIT" # The name of the company
  productName: "Catsh" # The name of the application
  productIdentifier: "catsh" # The unique product identifier
  description: "Universal terminal tools" # The application description
  copyright: "Copyright (c) 2025 TOY-KIT" # Copyright text
  comments: "Convenient terminal tools" # Comments
  version: "0.0.1" # The application version

repository:
  author: "lufuhu"
  email: "tk@lufuhu.com"
  url: "https://github.com/toy-kit/catsh"
  homepage: "http://tk.lufuhu.com/catsh/"