//go:build (!no_base || sqlserver) && !no_sqlserver

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "catsh/internal/database/drivers/sqlserver" // Microsoft SQL Server driver
)
