//go:build (all || most || maxcompute) && !no_maxcompute

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "catsh/service/database/drivers/maxcompute" // Alibaba MaxCompute driver
)
