// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Alert(arg1:string):Promise<void>;

export function CheckUpgrade():Promise<void>;

export function Load():Promise<types.LoadData>;

export function OpenAbout():Promise<void>;

export function QuestionDialog(arg1:string):Promise<boolean>;

export function SaveConf(arg1:types.Config):Promise<void>;
