// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1) {
  return window['go']['main']['App']['Alert'](arg1);
}

export function CheckUpgrade() {
  return window['go']['main']['App']['CheckUpgrade']();
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function OpenAbout() {
  return window['go']['main']['App']['OpenAbout']();
}

export function QuestionDialog(arg1) {
  return window['go']['main']['App']['QuestionDialog'](arg1);
}

export function SaveConf(arg1) {
  return window['go']['main']['App']['SaveConf'](arg1);
}
