// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function Load(): $CancellablePromise<types$0.AppData> {
    return $Call.ByID(2828703202).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveConfig(cfg: types$0.Config): $CancellablePromise<void> {
    return $Call.ByID(396592245, cfg);
}

// Private type creation functions
const $$createType0 = types$0.AppData.createFrom;
